apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-webapp
  namespace: passoapasso
  labels:
    {{- include "passoapasso.labels" . | nindent 4 }}
data:
{{- with .Values.deployment.container.variables.configMap }}
  {{- toYaml . | nindent 2 }}
{{- end }}
