apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-webapp
  namespace: passoapasso
  labels:
    {{- include "passoapasso.labels" . | nindent 4 }}
spec:
{{- if (.Values.deployment.replicaCount) -}} 
{{- if (.Values.deployment.autoscaling) -}} 
{{- if (not .Values.deployment.autoscaling.enabled) }}
  replicas: {{ .Values.deployment.replicaCount }}
{{- end }}
{{- end }}
{{- end }}
  selector:
    matchLabels:
      {{- include "passoapasso.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "passoapasso.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if (.Values.serviceAccount) -}} 
      {{- if (.Values.serviceAccount.create) -}} 
      {{- if (.Values.serviceAccountName) -}}
      serviceAccountName: {{ include "passoapasso.serviceAccountName" . }}
      {{- end }}
      {{- end }}
      {{- end }}
      {{- if .Values.podSecurityContext }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          {{- if .Values.securityContext }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.deployment.container.ports }}
          ports:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
            - name: MONGO_HOST
              valueFrom:
                configMapKeyRef:
                  key: MONGO_HOST
                  name: passoapasso-webapp
            - name: MONGO_PORT
              valueFrom:
                configMapKeyRef:
                  key: MONGO_PORT
                  name: passoapasso-webapp
            - name: MONGO_DATABASE
              valueFrom:
                configMapKeyRef:
                  key: MONGO_DATABASE
                  name: passoapasso-webapp
            - name: MONGO_USER
              valueFrom:
                secretKeyRef:
                  key: MONGO_USER
                  name: passoapasso-webapp
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: MONGO_PASSWORD
                  name: passoapasso-webapp
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
