apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-webapp
  namespace: passoapasso
  labels:
    {{- include "passoapasso.labels" . | nindent 4 }}
type: Opaque
data:
{{- with .Values.deployment.container.variables.secret }}
  {{- toYaml . | nindent 2 }}
{{- end }}
