{{- if (.Values.istio) -}} 
{{- if(.Values.istio.gateway) -}}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ .Release.Name }}-vs
  namespace: passoapasso
  labels:
    {{- include "passoapasso.labels" . | nindent 4 }}
spec:
  gateways:
    - {{ .Release.Name }}-gateway
  hosts:
    - {{ .Values.istio.gateway.host | quote }}
  http:
  - route:
    - destination:
        host: passoapasso-webapp.passoapasso.svc.cluster.local
        port:
          number: {{ .Values.service.targetPort }}
{{- end }}
{{- end }}
