apiVersion: v1
kind: Service
metadata:
    name: passo-a-passo-webapp
    namespace: passoapasso
    labels: {{- include "passo-a-passo.labels" . | nindent 4}}
spec:
    type: {{.Values.service.type}}
    ports:
        - name: http
          port: {{.Values.service.containerPort}}
          protocol: TCP
          targetPort: {{.Values.service.targetPort}}
    selector: {{- include "passo-a-passo.selectorLabels" . | nindent 4}}
